In [ ]:
!pip install transformers
!pip install datasets
!pip install torchaudio
!pip install soundfile
!pip install librosa
!pip install pandas
!pip install gdown
!pip install pythainlp
!pip install jiwer
!pip install evaluate

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.28.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Collecting datasets
  Downloading datasets-3.4.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.13)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.4.1-py3-none-any.whl (487 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.4/487.4 kB 9.6 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.6 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 11.9 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 16.5 MB/s eta 0:00:00
Installing collected packages: xxhash, dill, multiprocess, datasets
Successfully installed datasets-3.4.1 dill-0.3.8 multiprocess-0.70.16 xxhash-3.5.0
Requirement already satisfied: torchaudio in /usr/local/lib/python3.11/dist-packages (2.6.0+cu124)
Requirement already satisfied: torch==2.6.0 in /usr/local/lib/python3.11/dist-packages (from torchaudio) (2.6.0+cu124)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchaudio) (3.17.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchaudio) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchaudio) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchaudio) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchaudio) (2024.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch==2.6.0->torchaudio)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch==2.6.0->torchaudio)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch==2.6.0->torchaudio)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch==2.6.0->torchaudio)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch==2.6.0->torchaudio)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch==2.6.0->torchaudio)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch==2.6.0->torchaudio)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch==2.6.0->torchaudio)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch==2.6.0->torchaudio)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchaudio) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchaudio) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchaudio) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch==2.6.0->torchaudio)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchaudio) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch==2.6.0->torchaudio) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch==2.6.0->torchaudio) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch==2.6.0->torchaudio) (3.0.2)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 80.5 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 82.4 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 48.1 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.6 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 10.9 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 40.0 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 15.4 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 3.6 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 12.0 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127
Requirement already satisfied: soundfile in /usr/local/lib/python3.11/dist-packages (0.13.1)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.11/dist-packages (from soundfile) (1.17.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from soundfile) (2.0.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.0->soundfile) (2.22)
Requirement already satisfied: librosa in /usr/local/lib/python3.11/dist-packages (0.10.2.post1)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.11/dist-packages (from librosa) (3.0.1)
Requirement already satisfied: numpy!=1.22.0,!=1.22.1,!=1.22.2,>=1.20.3 in /usr/local/lib/python3.11/dist-packages (from librosa) (2.0.2)
Requirement already satisfied: scipy>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from librosa) (1.14.1)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=0.14 in /usr/local/lib/python3.11/dist-packages (from librosa) (1.4.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from librosa) (4.4.2)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.11/dist-packages (from librosa) (0.60.0)
Requirement already satisfied: soundfile>=0.12.1 in /usr/local/lib/python3.11/dist-packages (from librosa) (0.13.1)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.11/dist-packages (from librosa) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.11/dist-packages (from librosa) (0.5.0.post1)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from librosa) (4.12.2)
Requirement already satisfied: lazy-loader>=0.1 in /usr/local/lib/python3.11/dist-packages (from librosa) (0.4)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.11/dist-packages (from librosa) (1.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from lazy-loader>=0.1->librosa) (24.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.51.0->librosa) (0.43.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from pooch>=1.1->librosa) (4.3.6)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from pooch>=1.1->librosa) (2.32.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.20.0->librosa) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.11/dist-packages (from soundfile>=0.12.1->librosa) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.22)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2025.1.31)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: gdown in /usr/local/lib/python3.11/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown) (4.13.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from gdown) (3.17.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.11/dist-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2.3.0)

# **Load original data**

In [ ]:
folder_url = 'Your-dataset-folder-url-here'
!gdown {folder_url}

Downloading...
From (original): https://drive.google.com/uc?id=1ZVKX6YoYuc9zMpHy48WF-dUuE6Otz-Ks
From (redirected): https://drive.google.com/uc?id=1ZVKX6YoYuc9zMpHy48WF-dUuE6Otz-Ks&confirm=t&uuid=ec471920-1e01-40cf-bc80-dbfcf1f1f092
To: /content/cv-corpus-7.0-2021-07-21-th.tar.gz
100% 5.37G/5.37G [00:27<00:00, 193MB/s]

In [ ]:
otherFile_url = 'Your-dataset-folder-url-here'
!gdown --folder {otherFile_url}

Retrieving folder contents
Retrieving folder 1nbc3SXZYknCwv6q1BzOfrBRIRiveD47h Deepcut Dataset
Processing file 1anjFSXAuHYrw-jYVD2OOrUW_PE09Ckei test_dataset.tsv
Processing file 1E8TWwfUh8X6bVb5luuxFfDiEnNyVQYGn train_dataset.tsv
Processing file 1IAvFoExc2rtmsiv6IvDj-TMIS947jWIw valid_dataset.tsv
Retrieving folder 1FR9w5Lm7aRaLNS3XG025DySR_VjrpHvI lg data
Processing file 1ntXH7ewqSqIFdV_u3yLd4egjRvYllJUX tokenized_test.tsv
Processing file 1mW0sVXYPCkdJWUVm4FUfVmbA2ZetVSAy tokenized_train.tsv
Processing file 1sncZMEABl4TOYPj7kW9BrdFwAIGgpq_t tokenized_valid.tsv
Processing file 17S7YEIx_Yw1T48qFzfEkzv0PkanKIMd_ vocab.json
Retrieving folder 1ZGAqxacpj-zKQuOIn-kbEi9xU8R54H5g New Dataset
Processing file 1t7g2cxI46bgnYD_4kQ_DJSgrT1ieqEwD newDataset.tsv
Processing file 1HShAGrBVnaicDUy07xFPu_yXhQoWeQTL test_Dataset.tsv
Processing file 1qKCJ0AaYYm9kiU-E8B-mOlmLtBWLYW4R tokenized_test.tsv
Processing file 1RBe3gviyC-rh3_TPFfxbfo9zduTjrSSB tokenized_train.tsv
Processing file 13PU48N-gmgT6t6ZOflcMx1IRT34-Stdc tokenized_valid.tsv
Processing file 1kRIUqFqPa9uLp7bsSzxt1K0pR3SJc4NC train_Dataset.tsv
Processing file 1TsYEWfbCo2uvtk0jT_DdaebJdyvDDuZy valid_Dataset.tsv
Processing file 11UmKva_-GkxGvVQFze5iFcp9eL6C1hvB vocab.json
Processing file 1IFA2jma18V0fwiYls0mA4Hb65cPalnKq tokenized_test.tsv
Processing file 19XlcvizqkUl9lY2U-oH6BOq3DHxrrQUg tokenized_train.tsv
Processing file 1QByv4GuWC7tmZTqC5gOvO98zuLHPrv-V tokenized_valid.tsv
Processing file 1L1nBVF8OuCG7u9cHyv9QsYL4G7aWpmAV validated_cleaned.tsv
Processing file 1PbuPOFnBRYvRMEqPJM1M6M-1SCKFGfSj vocab.json
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1anjFSXAuHYrw-jYVD2OOrUW_PE09Ckei
To: /content/other files/Deepcut Dataset/test_dataset.tsv
100% 553k/553k [00:00<00:00, 123MB/s]
Downloading...
From: https://drive.google.com/uc?id=1E8TWwfUh8X6bVb5luuxFfDiEnNyVQYGn
To: /content/other files/Deepcut Dataset/train_dataset.tsv
100% 4.45M/4.45M [00:00<00:00, 22.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1IAvFoExc2rtmsiv6IvDj-TMIS947jWIw
To: /content/other files/Deepcut Dataset/valid_dataset.tsv
100% 558k/558k [00:00<00:00, 147MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ntXH7ewqSqIFdV_u3yLd4egjRvYllJUX
To: /content/other files/lg data/tokenized_test.tsv
100% 715k/715k [00:00<00:00, 116MB/s]
Downloading...
From: https://drive.google.com/uc?id=1mW0sVXYPCkdJWUVm4FUfVmbA2ZetVSAy
To: /content/other files/lg data/tokenized_train.tsv
100% 12.7M/12.7M [00:00<00:00, 66.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1sncZMEABl4TOYPj7kW9BrdFwAIGgpq_t
To: /content/other files/lg data/tokenized_valid.tsv
100% 703k/703k [00:00<00:00, 170MB/s]
Downloading...
From: https://drive.google.com/uc?id=17S7YEIx_Yw1T48qFzfEkzv0PkanKIMd_
To: /content/other files/lg data/vocab.json
100% 982/982 [00:00<00:00, 6.73MB/s]
Downloading...
From: https://drive.google.com/uc?id=1t7g2cxI46bgnYD_4kQ_DJSgrT1ieqEwD
To: /content/other files/New Dataset/newDataset.tsv
100% 11.5M/11.5M [00:00<00:00, 62.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1HShAGrBVnaicDUy07xFPu_yXhQoWeQTL
To: /content/other files/New Dataset/test_Dataset.tsv
100% 1.15M/1.15M [00:00<00:00, 111MB/s]
Downloading...
From: https://drive.google.com/uc?id=1qKCJ0AaYYm9kiU-E8B-mOlmLtBWLYW4R
To: /content/other files/New Dataset/tokenized_test.tsv
100% 553k/553k [00:00<00:00, 46.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1RBe3gviyC-rh3_TPFfxbfo9zduTjrSSB
To: /content/other files/New Dataset/tokenized_train.tsv
100% 4.45M/4.45M [00:00<00:00, 40.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=13PU48N-gmgT6t6ZOflcMx1IRT34-Stdc
To: /content/other files/New Dataset/tokenized_valid.tsv
100% 559k/559k [00:00<00:00, 117MB/s]
Downloading...
From: https://drive.google.com/uc?id=1kRIUqFqPa9uLp7bsSzxt1K0pR3SJc4NC
To: /content/other files/New Dataset/train_Dataset.tsv
100% 9.19M/9.19M [00:00<00:00, 27.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1TsYEWfbCo2uvtk0jT_DdaebJdyvDDuZy
To: /content/other files/New Dataset/valid_Dataset.tsv
100% 1.15M/1.15M [00:00<00:00, 39.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=11UmKva_-GkxGvVQFze5iFcp9eL6C1hvB
To: /content/other files/New Dataset/vocab.json
100% 1.46k/1.46k [00:00<00:00, 9.03MB/s]
Downloading...
From: https://drive.google.com/uc?id=1IFA2jma18V0fwiYls0mA4Hb65cPalnKq
To: /content/other files/tokenized_test.tsv
100% 1.31M/1.31M [00:00<00:00, 168MB/s]
Downloading...
From: https://drive.google.com/uc?id=19XlcvizqkUl9lY2U-oH6BOq3DHxrrQUg
To: /content/other files/tokenized_train.tsv
100% 2.93M/2.93M [00:00<00:00, 179MB/s]
Downloading...
From: https://drive.google.com/uc?id=1QByv4GuWC7tmZTqC5gOvO98zuLHPrv-V
To: /content/other files/tokenized_valid.tsv
100% 1.32M/1.32M [00:00<00:00, 185MB/s]
Downloading...
From: https://drive.google.com/uc?id=1L1nBVF8OuCG7u9cHyv9QsYL4G7aWpmAV
To: /content/other files/validated_cleaned.tsv
100% 13.2M/13.2M [00:00<00:00, 37.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1PbuPOFnBRYvRMEqPJM1M6M-1SCKFGfSj
To: /content/other files/vocab.json
100% 1.46k/1.46k [00:00<00:00, 10.4MB/s]
Download completed

In [ ]:
!tar -xvzf /content/cv-corpus-7.0-2021-07-21-th.tar.gz -C /content/

เอาต์พุตของการสตรีมมีการตัดเหลือเพียง 5000 บรรทัดสุดท้าย
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269603.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269604.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269606.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269608.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269609.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269611.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269613.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269615.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269616.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269617.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269618.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269619.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269682.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269683.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269684.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269685.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269686.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269690.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269691.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269692.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269693.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269694.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269700.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269701.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269702.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269703.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269704.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269705.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269706.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269707.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269708.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269709.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269710.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269711.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269712.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269713.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269714.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269715.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269716.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269717.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269718.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269719.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269720.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269721.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269723.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269724.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269727.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269729.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269731.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269733.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269734.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269735.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269736.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269737.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269738.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269739.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269740.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269741.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269742.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269743.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269744.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269750.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269751.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269752.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269753.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269754.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269755.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269756.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269757.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269758.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269759.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269760.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269761.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269762.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269763.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269764.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269765.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269766.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269767.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269768.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269769.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269770.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269771.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269772.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269773.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269774.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269780.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269781.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269782.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269783.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269784.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269785.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269786.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269787.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269788.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269789.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269790.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269791.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269792.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269793.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269794.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269795.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269796.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269797.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269798.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269799.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269800.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269801.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269802.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269803.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269804.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269805.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269806.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269807.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269808.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269809.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269810.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269811.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269812.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269813.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269814.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269815.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269816.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269817.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269818.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269819.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269820.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269821.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269822.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269823.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269824.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269825.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269826.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269827.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269828.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269829.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269830.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269831.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269832.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269833.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269834.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269835.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269836.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269837.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269838.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269839.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269840.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269841.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269842.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269844.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269846.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269850.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269851.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269852.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269853.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269854.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269855.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269856.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269857.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269858.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269859.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269860.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269861.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269862.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269863.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269864.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269865.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269866.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269867.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269868.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27269869.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27274921.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27274922.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27274923.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27274924.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27274926.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27274942.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27274944.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27274945.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27274946.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27274948.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27275468.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27275469.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27275470.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27275471.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27275472.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276080.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276081.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276082.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276083.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276084.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276106.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276107.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276108.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276109.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276110.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276113.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276114.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276115.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276116.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276117.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276203.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276204.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276205.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276206.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276207.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276225.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276226.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276227.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276228.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276229.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276235.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276236.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276237.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276238.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276239.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276380.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276381.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276383.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276384.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276385.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276421.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276423.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276425.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276426.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276427.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276501.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276503.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276504.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276505.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276506.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276541.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276542.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276543.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276544.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276545.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276566.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276568.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276571.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276572.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276573.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276598.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276599.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276601.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276602.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276603.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276761.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276763.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276764.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276766.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276767.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276787.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276788.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276789.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276790.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276791.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276834.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276837.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276839.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276840.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276842.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276878.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276879.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276880.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276881.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276882.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276910.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276912.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276913.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276914.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27276915.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277771.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277772.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277773.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277774.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277775.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277816.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277817.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277818.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277819.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277820.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277871.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277872.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277873.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277874.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27277880.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284489.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284490.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284491.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284492.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284493.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284499.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284500.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284501.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284502.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284503.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284504.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284505.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284506.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284507.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284508.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284897.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284898.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284899.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284900.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284901.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284907.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284908.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284909.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284910.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284911.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284912.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284913.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284914.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284915.mp3
cv-corpus-7.0-2021-07-21/th/clips/common_voice_th_27284916.mp3

In [ ]:
# from datasets import Dataset

# train_csv_path = "/content/cv-corpus-7.0-2021-07-21/th/train.tsv"
# test_csv_path = "/content/cv-corpus-7.0-2021-07-21/th/test.tsv"
# valid_csv_path = "/content/cv-corpus-7.0-2021-07-21/th/dev.tsv"

# common_voice_train = Dataset.from_csv(train_csv_path, delimiter='\t')
# common_voice_test = Dataset.from_csv(test_csv_path, delimiter='\t')
# common_voice_valid = Dataset.from_csv(valid_csv_path, delimiter='\t')

In [ ]:
from datasets import Dataset

train_csv_path = "/content/other files/tokenized_train.tsv"
test_csv_path = "/content/other files/tokenized_test.tsv"
valid_csv_path = "/content/other files/tokenized_valid.tsv"

common_voice_train = Dataset.from_csv(train_csv_path, delimiter='\t')
common_voice_test = Dataset.from_csv(test_csv_path, delimiter='\t')
common_voice_valid = Dataset.from_csv(valid_csv_path, delimiter='\t')

Generating train split: 0 examples [00:00, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

# **Prepare New Dataset**

In [ ]:
from datasets import Dataset

train_csv_path = "/content/cv-corpus-7.0-2021-07-21/th/train.tsv"
test_csv_path = "/content/cv-corpus-7.0-2021-07-21/th/test.tsv"
valid_csv_path = "/content/cv-corpus-7.0-2021-07-21/th/dev.tsv"

common_voice_train = Dataset.from_csv(train_csv_path, delimiter='\t')
common_voice_test = Dataset.from_csv(test_csv_path, delimiter='\t')
common_voice_valid = Dataset.from_csv(valid_csv_path, delimiter='\t')

In [ ]:
import pandas as pd

df_train = pd.DataFrame(common_voice_train)
df_test = pd.DataFrame(common_voice_test)
df_valid = pd.DataFrame(common_voice_valid)

In [ ]:
newDataset = pd.concat([df_train, df_test, df_valid])
newDataset

,client_id,path,sentence,up_votes,down_votes,age,gender,accent,locale,segment
0,f9bbd99da1cb2e67caaad540dc7e002822474645a5d27a...,common_voice_th_25686161.mp3,มันเป็นเรื่องที่ดีที่การเดินทางย้อนเวลาไม่ได้ม...,2,0,fourties,male,None,th,None
1,f9bbd99da1cb2e67caaad540dc7e002822474645a5d27a...,common_voice_th_25686166.mp3,เขาต้องมีส่วนรู้เห็นกับอาชญากรรมนี้แน่,2,0,fourties,male,None,th,None
2,f9bbd99da1cb2e67caaad540dc7e002822474645a5d27a...,common_voice_th_25897915.mp3,ที่ทำการไปรษณีย์จะทำการหยุดตัวอักษรหรือโทรเลข ...,2,0,fourties,male,None,th,None
3,f9bbd99da1cb2e67caaad540dc7e002822474645a5d27a...,common_voice_th_25897916.mp3,บนเพดานของห้องส่วนใหญ่ยังคงไม่บุบสลาย แต่ก็ยัง...,2,0,fourties,male,None,th,None
4,f9bbd99da1cb2e67caaad540dc7e002822474645a5d27a...,common_voice_th_25897918.mp3,มันคือความอับอาย บริสุทธิ์และง่าย,2,0,fourties,male,None,th,None
...,...,...,...,...,...,...,...,...,...,...
9707,c5b6623009cc28257e4abe4a05bac0e429a2853776d94e...,common_voice_th_27380641.mp3,โครงการยี่สิบล้านดอลลาร์มุ่งเป้าให้เสร็จในแปดส...,2,0,twenties,female,None,th,None
9708,c5b6623009cc28257e4abe4a05bac0e429a2853776d94e...,common_voice_th_27380642.mp3,ค้นพบว่าการเดินทางคนเดียวดีกว่ามีเพื่อนร่วมทาง...,2,0,twenties,female,None,th,None
9709,d41b81fea7821a5aeeb6aeb6c44988531007b5ddd6bbac...,common_voice_th_25660313.mp3,ไม่มีไฟโดยไม่มีควัน,2,0,None,None,None,th,None
9710,d41b81fea7821a5aeeb6aeb6c44988531007b5ddd6bbac...,common_voice_th_25660344.mp3,เธอไปที่ร้านขายยาเพื่อรับยา,2,0,None,None,None,th,None
9711,d41b81fea7821a5aeeb6aeb6c44988531007b5ddd6bbac...,common_voice_th_25660610.mp3,โอ้ที่รักไม่ได้พลาดเขาพูด,2,1,None,None,None,th,None

In [ ]:
newDataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42756 entries, 0 to 9711
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   client_id   42756 non-null  object
 1   path        42756 non-null  object
 2   sentence    42756 non-null  object
 3   up_votes    42756 non-null  int64
 4   down_votes  42756 non-null  int64
 5   age         22548 non-null  object
 6   gender      22551 non-null  object
 7   accent      0 non-null      object
 8   locale      42756 non-null  object
 9   segment     5 non-null      object
dtypes: int64(2), object(8)
memory usage: 4.6+ MB

In [ ]:
newDataset.shape

(42756, 10)

In [ ]:
newDataset.to_csv('newDataset.tsv', sep='\t', index=False)

In [ ]:
from datasets import Dataset

common_voice_dataset = Dataset.from_csv('/content/other files/New Dataset/newDataset.tsv', delimiter='\t')

In [ ]:
print(common_voice_dataset.column_names)

['client_id', 'path', 'sentence', 'up_votes', 'down_votes', 'age', 'gender', 'accent', 'locale', 'segment']

In [ ]:
# Split the dataset into 80% train and 20% test+valid
train_testvalid = common_voice_dataset.train_test_split(test_size=0.2, seed=42)

# Split the 20% test set into 50% valid and 50% test
test_valid = train_testvalid['test'].train_test_split(test_size=0.5, seed=42)

# Now you have the train, valid, and test sets
train_dataset = train_testvalid['train']
valid_dataset = test_valid['train']
test_dataset = test_valid['test']

In [ ]:
train_dataset.to_pandas().to_csv('train_Dataset.tsv', sep='\t', index=False)
valid_dataset.to_pandas().to_csv('valid_Dataset.tsv', sep='\t', index=False)
test_dataset.to_pandas().to_csv('test_Dataset.tsv', sep='\t', index=False)

In [ ]:
train_df = pd.read_csv('train_Dataset.tsv', sep='\t')

In [ ]:
train_df.head(5)

,client_id,path,sentence,up_votes,down_votes,age,gender,accent,locale,segment
0,cae93a67c037530d58d1d4332d69a631f5a4189e44d830...,common_voice_th_25936033.mp3,และเสียงของเธอก็จมไปในเสียงกระซิบ เสียงหัวเราะ...,2,0,teens,male,NaN,th,NaN
1,79e1c16f109709cef324603d132e0246ed7302f0c71f79...,common_voice_th_26384829.mp3,โคมไฟตั้งโต๊ะ,2,0,fifties,female,NaN,th,NaN
2,b82d60a9e9734fa74f7a75cb51ab01ca25fa1efb17a261...,common_voice_th_23659392.mp3,เขามีสวนหลังบ้านที่มีภูมิทัศน์สวยงามมาก,2,0,NaN,NaN,NaN,th,NaN
3,52870910c63fbc5f20abd78872c5b45dd1c05649a9774c...,common_voice_th_27395454.mp3,ให้คณะกรรมการการเลือกตั้ง เอาไปพ่วงถามด้วย,2,0,teens,male,NaN,th,NaN
4,b6c59587329354f519326f7a1916334d6ecaf17bbc20aa...,common_voice_th_25669650.mp3,ขอบคุณจากใจ,2,0,thirties,female,NaN,th,NaN

# **Load New Dataset**

In [ ]:
from datasets import Dataset

train_csv_path = "/content/other files/Deepcut Dataset/train_dataset.tsv"
test_csv_path = "/content/other files/Deepcut Dataset/test_dataset.tsv"
valid_csv_path = "/content/other files/Deepcut Dataset/valid_dataset.tsv"

common_voice_train = Dataset.from_csv(train_csv_path, delimiter='\t')
common_voice_test = Dataset.from_csv(test_csv_path, delimiter='\t')
common_voice_valid = Dataset.from_csv(valid_csv_path, delimiter='\t')

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
common_voice_train

Dataset({
    features: ['path', 'sentence'],
    num_rows: 34204
})

In [ ]:
common_voice_valid

Dataset({
    features: ['path', 'sentence'],
    num_rows: 4276
})

# **Load New Dataset (lg)**

In [ ]:
from datasets import Dataset

train_csv_path = "/content/other files/lg data/tokenized_train.tsv"
test_csv_path = "/content/other files/lg data/tokenized_test.tsv"
valid_csv_path = "/content/other files/lg data/tokenized_valid.tsv"

common_voice_train = Dataset.from_csv(train_csv_path, delimiter='\t')
common_voice_test = Dataset.from_csv(test_csv_path, delimiter='\t')
common_voice_valid = Dataset.from_csv(valid_csv_path, delimiter='\t')

Generating train split: 0 examples [00:00, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

# **Explore Dataset**

In [ ]:
import pandas as pd

df_train = pd.DataFrame(common_voice_train)
df_test = pd.DataFrame(common_voice_test)
df_valid = pd.DataFrame(common_voice_valid)

In [ ]:
df_train.head(1)

,client_id,path,sentence,up_votes,down_votes,age,gender,accent,locale,segment
0,f9bbd99da1cb2e67caaad540dc7e002822474645a5d27a...,common_voice_th_25686161.mp3,มันเป็นเรื่องที่ดีที่การเดินทางย้อนเวลาไม่ได้ม...,2,0,fourties,male,None,th,None

In [ ]:
df_train.shape

(23332, 10)

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23332 entries, 0 to 23331
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   client_id   23332 non-null  object
 1   path        23332 non-null  object
 2   sentence    23332 non-null  object
 3   up_votes    23332 non-null  int64
 4   down_votes  23332 non-null  int64
 5   age         18795 non-null  object
 6   gender      18795 non-null  object
 7   accent      0 non-null      object
 8   locale      23332 non-null  object
 9   segment     4 non-null      object
dtypes: int64(2), object(8)
memory usage: 1.8+ MB

In [ ]:
df_test.head(1)

,client_id,path,sentence,up_votes,down_votes,age,gender,accent,locale,segment
0,00086f5dc46f9038f13bbd829c4118fab3ac28688d5ee8...,common_voice_th_25695281.mp3,ใครเป็นผู้รับ,2,0,None,None,None,th,None

In [ ]:
df_test.shape

(9712, 10)

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   client_id   9712 non-null   object
 1   path        9712 non-null   object
 2   sentence    9712 non-null   object
 3   up_votes    9712 non-null   int64
 4   down_votes  9712 non-null   int64
 5   age         455 non-null    object
 6   gender      455 non-null    object
 7   accent      0 non-null      object
 8   locale      9712 non-null   object
 9   segment     1 non-null      object
dtypes: int64(2), object(8)
memory usage: 758.9+ KB

# **Drop Column to path and sentence**

In [ ]:
common_voice_train = common_voice_train.remove_columns(["accent", "age", "client_id", "down_votes", "gender", "locale", "segment", "up_votes"])
common_voice_test = common_voice_test.remove_columns(["accent", "age", "client_id", "down_votes", "gender", "locale", "segment", "up_votes"])
common_voice_valid = common_voice_valid.remove_columns(["accent", "age", "client_id", "down_votes", "gender", "locale", "segment", "up_votes"])

# **Func to show data**

In [ ]:
from datasets import ClassLabel
import random
import pandas as pd
from IPython.display import display, HTML

def show_random_elements(dataset, num_examples=10):
    assert num_examples <= len(dataset), "Can't pick more elements than there are in the dataset."
    picks = []
    for _ in range(num_examples):
        pick = random.randint(0, len(dataset)-1)
        while pick in picks:
            pick = random.randint(0, len(dataset)-1)
        picks.append(pick)

    df = pd.DataFrame(dataset[picks])
    display(HTML(df.to_html()))

In [ ]:
show_random_elements(common_voice_train.remove_columns(["path"]), num_examples=20)

# **Tokenizer**

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import re
from pythainlp.tokenize import word_tokenize

chars_to_ignore_regex = '[\,\?\.\!\-\;\:\"\“\%\‘\”\�]'

def th_tokenize(batch):
    batch["sentence"] = " ".join(word_tokenize(batch["sentence"], engine="attacut"))
    return batch

def remove_special_characters(batch):
    batch["sentence"] = re.sub(chars_to_ignore_regex, '', batch["sentence"]).lower() + " "
    return batch

In [ ]:
common_voice_train = common_voice_train.map(th_tokenize).map(remove_special_characters)

Map:   0%|          | 0/34204 [00:00<?, ? examples/s]

NotFoundError: Graph execution error:

Detected at node StatefulPartitionedCall defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>

  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance

  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 619, in start

  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start

  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever

  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once

  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run

  File "/usr/local/lib/python3.11/dist-packages/tornado/ioloop.py", line 699, in <lambda>

  File "/usr/local/lib/python3.11/dist-packages/tornado/ioloop.py", line 750, in _run_callback

  File "/usr/local/lib/python3.11/dist-packages/tornado/gen.py", line 824, in inner

  File "/usr/local/lib/python3.11/dist-packages/tornado/gen.py", line 785, in run

  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 361, in process_one

  File "/usr/local/lib/python3.11/dist-packages/tornado/gen.py", line 233, in wrapper

  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell

  File "/usr/local/lib/python3.11/dist-packages/tornado/gen.py", line 233, in wrapper

  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request

  File "/usr/local/lib/python3.11/dist-packages/tornado/gen.py", line 233, in wrapper

  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute

  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell

  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell

  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell

  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner

  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async

  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes

  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code

  File "<ipython-input-12-193a8d05512a>", line 1, in <cell line: 0>

  File "/usr/local/lib/python3.11/dist-packages/datasets/arrow_dataset.py", line 562, in wrapper

  File "/usr/local/lib/python3.11/dist-packages/datasets/arrow_dataset.py", line 3079, in map

  File "/usr/local/lib/python3.11/dist-packages/datasets/arrow_dataset.py", line 3487, in _map_single

  File "/usr/local/lib/python3.11/dist-packages/datasets/arrow_dataset.py", line 3461, in iter_outputs

  File "/usr/local/lib/python3.11/dist-packages/datasets/arrow_dataset.py", line 3390, in apply_function

  File "<ipython-input-11-c02d8723b2db>", line 7, in th_tokenize

  File "/usr/local/lib/python3.11/dist-packages/pythainlp/tokenize/core.py", line 277, in word_tokenize

  File "/usr/local/lib/python3.11/dist-packages/pythainlp/tokenize/deepcut.py", line 35, in segment

  File "/usr/local/lib/python3.11/dist-packages/deepcut/deepcut.py", line 47, in tokenize

  File "/usr/local/lib/python3.11/dist-packages/deepcut/deepcut.py", line 299, in tokenize

  File "/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/usr/local/lib/python3.11/dist-packages/keras/src/backend/tensorflow/trainer.py", line 562, in predict

  File "/usr/local/lib/python3.11/dist-packages/keras/src/backend/tensorflow/trainer.py", line 259, in one_step_on_data_distributed

could not find registered transfer manager for platform Host -- check target linkage
	 [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2804]

In [ ]:
show_random_elements(common_voice_train)

In [ ]:
common_voice_test = common_voice_test.map(th_tokenize).map(remove_special_characters)

Map:   0%|          | 0/4276 [00:00<?, ? examples/s]

Map:   0%|          | 0/4276 [00:00<?, ? examples/s]

In [ ]:
show_random_elements(common_voice_test)

In [ ]:
common_voice_valid = common_voice_valid.map(th_tokenize).map(remove_special_characters)

Map:   0%|          | 0/4276 [00:00<?, ? examples/s]

Map:   0%|          | 0/4276 [00:00<?, ? examples/s]

In [ ]:
show_random_elements(common_voice_valid)

# **Save tokenized data to csv**

In [ ]:
common_voice_train.shape

(34204, 2)

In [ ]:
# common_voice_test.shape

In [ ]:
common_voice_valid.shape

(4276, 2)

In [ ]:
tokenized_train = "/content/tokenized_train.tsv"
tokenized_valid = "/content/tokenized_valid.tsv"
tokenized_test = "/content/tokenized_test.tsv"

# Save processed datasets to CSV
common_voice_train.to_csv(tokenized_train, sep='\t', index=False, encoding='utf-8')
common_voice_valid.to_csv(tokenized_valid, sep='\t', index=False, encoding='utf-8')
common_voice_test.to_csv(tokenized_test, sep='\t', index=False, encoding='utf-8')

Creating CSV from Arrow format:   0%|          | 0/35 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/5 [00:00<?, ?ba/s]

Creating CSV from Arrow format:   0%|          | 0/5 [00:00<?, ?ba/s]

553400

In [ ]:
from google.colab import files

files.download(tokenized_train)
files.download(tokenized_test)
files.download(tokenized_valid)

In [ ]:
path_test = "/content/tokenized_test.tsv"

test01 = Dataset.from_csv(path_test, delimiter='\t')

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
show_random_elements(test01)

In [ ]:
show_random_elements(common_voice_test)

# **Create Vocab**

In [ ]:
def extract_all_chars(batch):
  all_text = " ".join(batch["sentence"])
  vocab = list(set(all_text))
  return {"vocab": [vocab], "all_text": [all_text]}

In [ ]:
vocab_train = common_voice_train.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_train.column_names)
vocab_test = common_voice_test.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_test.column_names)
vocab_valid = common_voice_valid.map(extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True, remove_columns=common_voice_valid.column_names)

Map:   0%|          | 0/34204 [00:00<?, ? examples/s]

Map:   0%|          | 0/4276 [00:00<?, ? examples/s]

Map:   0%|          | 0/4276 [00:00<?, ? examples/s]

In [ ]:
vocab_list = sorted(set(vocab_train["vocab"][0]) | set(vocab_test["vocab"][0]) | set(vocab_valid["vocab"][0]))

In [ ]:
vocab_dict = {v: k for k, v in enumerate(vocab_list)}
print("len vocab: {}".format(len(vocab_dict)))
vocab_dict

len vocab: 92

{' ': 0,
 'a': 1,
 'b': 2,
 'c': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'r': 16,
 's': 17,
 't': 18,
 'u': 19,
 'w': 20,
 'x': 21,
 'y': 22,
 'ก': 23,
 'ข': 24,
 'ฃ': 25,
 'ค': 26,
 'ฆ': 27,
 'ง': 28,
 'จ': 29,
 'ฉ': 30,
 'ช': 31,
 'ซ': 32,
 'ฌ': 33,
 'ญ': 34,
 'ฎ': 35,
 'ฏ': 36,
 'ฐ': 37,
 'ฑ': 38,
 'ฒ': 39,
 'ณ': 40,
 'ด': 41,
 'ต': 42,
 'ถ': 43,
 'ท': 44,
 'ธ': 45,
 'น': 46,
 'บ': 47,
 'ป': 48,
 'ผ': 49,
 'ฝ': 50,
 'พ': 51,
 'ฟ': 52,
 'ภ': 53,
 'ม': 54,
 'ย': 55,
 'ร': 56,
 'ฤ': 57,
 'ล': 58,
 'ว': 59,
 'ศ': 60,
 'ษ': 61,
 'ส': 62,
 'ห': 63,
 'ฬ': 64,
 'อ': 65,
 'ฮ': 66,
 'ฯ': 67,
 'ะ': 68,
 'ั': 69,
 'า': 70,
 'ำ': 71,
 'ิ': 72,
 'ี': 73,
 'ึ': 74,
 'ื': 75,
 'ุ': 76,
 'ู': 77,
 'เ': 78,
 'แ': 79,
 'โ': 80,
 'ใ': 81,
 'ไ': 82,
 'ๅ': 83,
 'ๆ': 84,
 '็': 85,
 '่': 86,
 '้': 87,
 '๊': 88,
 '๋': 89,
 '์': 90,
 'ํ': 91}

In [ ]:
vocab_dict["|"] = vocab_dict[" "]
del vocab_dict[" "]

In [ ]:
print("len vocab: {}".format(len(vocab_dict)))
vocab_dict

len vocab: 92

{'a': 1,
 'b': 2,
 'c': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'r': 16,
 's': 17,
 't': 18,
 'u': 19,
 'w': 20,
 'x': 21,
 'y': 22,
 'ก': 23,
 'ข': 24,
 'ฃ': 25,
 'ค': 26,
 'ฆ': 27,
 'ง': 28,
 'จ': 29,
 'ฉ': 30,
 'ช': 31,
 'ซ': 32,
 'ฌ': 33,
 'ญ': 34,
 'ฎ': 35,
 'ฏ': 36,
 'ฐ': 37,
 'ฑ': 38,
 'ฒ': 39,
 'ณ': 40,
 'ด': 41,
 'ต': 42,
 'ถ': 43,
 'ท': 44,
 'ธ': 45,
 'น': 46,
 'บ': 47,
 'ป': 48,
 'ผ': 49,
 'ฝ': 50,
 'พ': 51,
 'ฟ': 52,
 'ภ': 53,
 'ม': 54,
 'ย': 55,
 'ร': 56,
 'ฤ': 57,
 'ล': 58,
 'ว': 59,
 'ศ': 60,
 'ษ': 61,
 'ส': 62,
 'ห': 63,
 'ฬ': 64,
 'อ': 65,
 'ฮ': 66,
 'ฯ': 67,
 'ะ': 68,
 'ั': 69,
 'า': 70,
 'ำ': 71,
 'ิ': 72,
 'ี': 73,
 'ึ': 74,
 'ื': 75,
 'ุ': 76,
 'ู': 77,
 'เ': 78,
 'แ': 79,
 'โ': 80,
 'ใ': 81,
 'ไ': 82,
 'ๅ': 83,
 'ๆ': 84,
 '็': 85,
 '่': 86,
 '้': 87,
 '๊': 88,
 '๋': 89,
 '์': 90,
 'ํ': 91,
 '|': 0}

In [ ]:
vocab_dict["[UNK]"] = len(vocab_dict)
vocab_dict["[PAD]"] = len(vocab_dict)
len(vocab_dict)

94

In [ ]:
vocab_dict

{'a': 1,
 'b': 2,
 'c': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'r': 16,
 's': 17,
 't': 18,
 'u': 19,
 'w': 20,
 'x': 21,
 'y': 22,
 'ก': 23,
 'ข': 24,
 'ฃ': 25,
 'ค': 26,
 'ฆ': 27,
 'ง': 28,
 'จ': 29,
 'ฉ': 30,
 'ช': 31,
 'ซ': 32,
 'ฌ': 33,
 'ญ': 34,
 'ฎ': 35,
 'ฏ': 36,
 'ฐ': 37,
 'ฑ': 38,
 'ฒ': 39,
 'ณ': 40,
 'ด': 41,
 'ต': 42,
 'ถ': 43,
 'ท': 44,
 'ธ': 45,
 'น': 46,
 'บ': 47,
 'ป': 48,
 'ผ': 49,
 'ฝ': 50,
 'พ': 51,
 'ฟ': 52,
 'ภ': 53,
 'ม': 54,
 'ย': 55,
 'ร': 56,
 'ฤ': 57,
 'ล': 58,
 'ว': 59,
 'ศ': 60,
 'ษ': 61,
 'ส': 62,
 'ห': 63,
 'ฬ': 64,
 'อ': 65,
 'ฮ': 66,
 'ฯ': 67,
 'ะ': 68,
 'ั': 69,
 'า': 70,
 'ำ': 71,
 'ิ': 72,
 'ี': 73,
 'ึ': 74,
 'ื': 75,
 'ุ': 76,
 'ู': 77,
 'เ': 78,
 'แ': 79,
 'โ': 80,
 'ใ': 81,
 'ไ': 82,
 'ๅ': 83,
 'ๆ': 84,
 '็': 85,
 '่': 86,
 '้': 87,
 '๊': 88,
 '๋': 89,
 '์': 90,
 'ํ': 91,
 '|': 0,
 '[UNK]': 92,
 '[PAD]': 93}

In [ ]:
unwanted_chars = set(["~", "’", "'","—"])

vocab_dict = {char: idx for char, idx in vocab_dict.items() if char not in unwanted_chars}

In [ ]:
print("len vocab: {}".format(len(vocab_dict)))
vocab_dict

len vocab: 94

{'a': 1,
 'b': 2,
 'c': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'r': 16,
 's': 17,
 't': 18,
 'u': 19,
 'w': 20,
 'x': 21,
 'y': 22,
 'ก': 23,
 'ข': 24,
 'ฃ': 25,
 'ค': 26,
 'ฆ': 27,
 'ง': 28,
 'จ': 29,
 'ฉ': 30,
 'ช': 31,
 'ซ': 32,
 'ฌ': 33,
 'ญ': 34,
 'ฎ': 35,
 'ฏ': 36,
 'ฐ': 37,
 'ฑ': 38,
 'ฒ': 39,
 'ณ': 40,
 'ด': 41,
 'ต': 42,
 'ถ': 43,
 'ท': 44,
 'ธ': 45,
 'น': 46,
 'บ': 47,
 'ป': 48,
 'ผ': 49,
 'ฝ': 50,
 'พ': 51,
 'ฟ': 52,
 'ภ': 53,
 'ม': 54,
 'ย': 55,
 'ร': 56,
 'ฤ': 57,
 'ล': 58,
 'ว': 59,
 'ศ': 60,
 'ษ': 61,
 'ส': 62,
 'ห': 63,
 'ฬ': 64,
 'อ': 65,
 'ฮ': 66,
 'ฯ': 67,
 'ะ': 68,
 'ั': 69,
 'า': 70,
 'ำ': 71,
 'ิ': 72,
 'ี': 73,
 'ึ': 74,
 'ื': 75,
 'ุ': 76,
 'ู': 77,
 'เ': 78,
 'แ': 79,
 'โ': 80,
 'ใ': 81,
 'ไ': 82,
 'ๅ': 83,
 'ๆ': 84,
 '็': 85,
 '่': 86,
 '้': 87,
 '๊': 88,
 '๋': 89,
 '์': 90,
 'ํ': 91,
 '|': 0,
 '[UNK]': 92,
 '[PAD]': 93}

In [ ]:
vocab_dict = {char: idx for idx, (char, _) in enumerate(vocab_dict.items())}
vocab_dict

{'a': 0,
 'b': 1,
 'c': 2,
 'e': 3,
 'f': 4,
 'g': 5,
 'h': 6,
 'i': 7,
 'j': 8,
 'k': 9,
 'l': 10,
 'm': 11,
 'n': 12,
 'o': 13,
 'p': 14,
 'r': 15,
 's': 16,
 't': 17,
 'u': 18,
 'w': 19,
 'x': 20,
 'y': 21,
 'ก': 22,
 'ข': 23,
 'ฃ': 24,
 'ค': 25,
 'ฆ': 26,
 'ง': 27,
 'จ': 28,
 'ฉ': 29,
 'ช': 30,
 'ซ': 31,
 'ฌ': 32,
 'ญ': 33,
 'ฎ': 34,
 'ฏ': 35,
 'ฐ': 36,
 'ฑ': 37,
 'ฒ': 38,
 'ณ': 39,
 'ด': 40,
 'ต': 41,
 'ถ': 42,
 'ท': 43,
 'ธ': 44,
 'น': 45,
 'บ': 46,
 'ป': 47,
 'ผ': 48,
 'ฝ': 49,
 'พ': 50,
 'ฟ': 51,
 'ภ': 52,
 'ม': 53,
 'ย': 54,
 'ร': 55,
 'ฤ': 56,
 'ล': 57,
 'ว': 58,
 'ศ': 59,
 'ษ': 60,
 'ส': 61,
 'ห': 62,
 'ฬ': 63,
 'อ': 64,
 'ฮ': 65,
 'ฯ': 66,
 'ะ': 67,
 'ั': 68,
 'า': 69,
 'ำ': 70,
 'ิ': 71,
 'ี': 72,
 'ึ': 73,
 'ื': 74,
 'ุ': 75,
 'ู': 76,
 'เ': 77,
 'แ': 78,
 'โ': 79,
 'ใ': 80,
 'ไ': 81,
 'ๅ': 82,
 'ๆ': 83,
 '็': 84,
 '่': 85,
 '้': 86,
 '๊': 87,
 '๋': 88,
 '์': 89,
 'ํ': 90,
 '|': 91,
 '[UNK]': 92,
 '[PAD]': 93}

In [ ]:
print("same index :", len(vocab_dict) != len(set(vocab_dict.values())))

same index : False

In [ ]:
import json
with open('vocab.json', 'w', encoding='utf-8') as vocab_file:
    json.dump(vocab_dict, vocab_file, ensure_ascii=False)

# **Load model**

In [ ]:
from transformers import Wav2Vec2CTCTokenizer

tokenizer = Wav2Vec2CTCTokenizer("/content/vocab.json", unk_token="[UNK]", pad_token="[PAD]", word_delimiter_token="|")

In [ ]:
from transformers import Wav2Vec2FeatureExtractor

feature_extractor = Wav2Vec2FeatureExtractor(feature_size=1, sampling_rate=16000, padding_value=0.0, do_normalize=True, return_attention_mask=True)

In [ ]:
from transformers import Wav2Vec2Processor

processor = Wav2Vec2Processor(feature_extractor=feature_extractor, tokenizer=tokenizer)

In [ ]:
from transformers import Wav2Vec2ForCTC

model = Wav2Vec2ForCTC.from_pretrained(
    "facebook/wav2vec2-large-xlsr-53",
    attention_dropout=0.1,
    hidden_dropout=0.1,
    feat_proj_dropout=0.0,
    mask_time_prob=0.05,
    layerdrop=0.1,
    gradient_checkpointing=True,
    ctc_loss_reduction="mean",
    pad_token_id=processor.tokenizer.pad_token_id,
    vocab_size=len(processor.tokenizer),
    ignore_mismatched_sizes=True,
)

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-large-xlsr-53 and are newly initialized: ['lm_head.bias', 'lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
# from transformers import Wav2Vec2ForCTC

# model = Wav2Vec2ForCTC.from_pretrained(
#     "/content/gdrive/MyDrive/material project sm/model/7000rows",
#     attention_dropout=0.1,
#     hidden_dropout=0.1,
#     feat_proj_dropout=0.0,
#     mask_time_prob=0.05,
#     layerdrop=0.1,
#     # gradient_checkpointing=True,
#     ctc_loss_reduction="mean",
#     pad_token_id=processor.tokenizer.pad_token_id,
#     vocab_size=len(processor.tokenizer),
#     ignore_mismatched_sizes=True,
# )

# **Preprocess Data**

In [ ]:
import torchaudio
import os

def speech_file_to_array_fn(batch):
    audio_file_path = os.path.join("/content/cv-corpus-7.0-2021-07-21/th/clips", batch["path"])

    if not os.path.exists(audio_file_path):
        print(f"File does not exist: {audio_file_path}")
        return batch

    speech_array, sampling_rate = torchaudio.load(audio_file_path)
    batch["speech"] = speech_array[0].numpy()
    batch["sampling_rate"] = sampling_rate
    batch["target_text"] = batch["sentence"]
    return batch

In [ ]:
# train = train_splits.map(speech_file_to_array_fn, remove_columns=train_splits.column_names)
# test = common_voice_test.map(speech_file_to_array_fn, remove_columns=common_voice_test.column_names)
# valid = common_voice_valid.map(speech_file_to_array_fn, remove_columns=common_voice_valid.column_names)

In [ ]:
train = common_voice_train.map(speech_file_to_array_fn, remove_columns=common_voice_train.column_names)
valid = common_voice_valid.map(speech_file_to_array_fn, remove_columns=common_voice_valid.column_names)

Map:   0%|          | 0/34204 [00:00<?, ? examples/s]

Map:   0%|          | 0/4276 [00:00<?, ? examples/s]

In [ ]:
import librosa
import numpy as np

def resample(batch):
    speech_array = np.asarray(batch["speech"])

    speech_resampled = librosa.resample(speech_array, orig_sr=48_000, target_sr=16_000)

    batch["speech"] = speech_resampled
    batch["sampling_rate"] = 16_000
    return batch

In [ ]:
train = train.map(resample, num_proc=4)
valid = valid.map(resample, num_proc=4)

Map (num_proc=4):   0%|          | 0/34204 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/4276 [00:00<?, ? examples/s]

In [ ]:
def prepare_dataset(batch):
    # check that all files have the correct sampling rate
    assert (
        len(set(batch["sampling_rate"])) == 1
    ), f"Make sure all inputs have the same sampling rate of {processor.feature_extractor.sampling_rate}."

    batch["input_values"] = processor(batch["speech"], sampling_rate=batch["sampling_rate"][0]).input_values

    with processor.as_target_processor():
        batch["labels"] = processor(batch["target_text"]).input_ids
    return batch

In [ ]:
train = train.map(prepare_dataset, remove_columns=train.column_names, batch_size=8, num_proc=4, batched=True)

Map (num_proc=4):   0%|          | 0/34204 [00:00<?, ? examples/s]

/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(

In [ ]:
valid = valid.map(prepare_dataset, remove_columns=valid.column_names, batch_size=8, num_proc=4, batched=True)

Map (num_proc=4):   0%|          | 0/4276 [00:00<?, ? examples/s]

/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(

# **Setting for train**

In [ ]:
import torch

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Union

@dataclass
class DataCollatorCTCWithPadding:
    """
    Data collator that will dynamically pad the inputs received.
    Args:
        processor (:class:`~transformers.Wav2Vec2Processor`)
            The processor used for proccessing the data.
        padding (:obj:`bool`, :obj:`str` or :class:`~transformers.tokenization_utils_base.PaddingStrategy`, `optional`, defaults to :obj:`True`):
            Select a strategy to pad the returned sequences (according to the model's padding side and padding index)
            among:
            * :obj:`True` or :obj:`'longest'`: Pad to the longest sequence in the batch (or no padding if only a single
              sequence if provided).
            * :obj:`'max_length'`: Pad to a maximum length specified with the argument :obj:`max_length` or to the
              maximum acceptable input length for the model if that argument is not provided.
            * :obj:`False` or :obj:`'do_not_pad'` (default): No padding (i.e., can output a batch with sequences of
              different lengths).
        max_length (:obj:`int`, `optional`):
            Maximum length of the ``input_values`` of the returned list and optionally padding length (see above).
        max_length_labels (:obj:`int`, `optional`):
            Maximum length of the ``labels`` returned list and optionally padding length (see above).
        pad_to_multiple_of (:obj:`int`, `optional`):
            If set will pad the sequence to a multiple of the provided value.
            This is especially useful to enable the use of Tensor Cores on NVIDIA hardware with compute capability >=
            7.5 (Volta).
    """

    processor: Wav2Vec2Processor
    padding: Union[bool, str] = True
    max_length: Optional[int] = None
    max_length_labels: Optional[int] = None
    pad_to_multiple_of: Optional[int] = None
    pad_to_multiple_of_labels: Optional[int] = None

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        # split inputs and labels since they have to be of different lenghts and need
        # different padding methods
        input_features = [{"input_values": feature["input_values"]} for feature in features]
        label_features = [{"input_ids": feature["labels"]} for feature in features]

        batch = self.processor.pad(
            input_features,
            padding=self.padding,
            max_length=self.max_length,
            pad_to_multiple_of=self.pad_to_multiple_of,
            return_tensors="pt",
        )
        with self.processor.as_target_processor():
            labels_batch = self.processor.pad(
                label_features,
                padding=self.padding,
                max_length=self.max_length_labels,
                pad_to_multiple_of=self.pad_to_multiple_of_labels,
                return_tensors="pt",
            )

        # replace padding with -100 to ignore loss correctly
        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)

        batch["labels"] = labels

        return batch

In [ ]:
data_collator = DataCollatorCTCWithPadding(processor=processor, padding=True)

In [ ]:
import evaluate

wer_metric = evaluate.load("wer")
cer_metric = evaluate.load("cer")

Downloading builder script:   0%|          | 0.00/4.49k [00:00<?, ?B/s]

Downloading builder script:   0%|          | 0.00/5.60k [00:00<?, ?B/s]

In [ ]:
def compute_metrics(pred):
    pred_logits = pred.predictions
    pred_ids = np.argmax(pred_logits, axis=-1)

    pred.label_ids[pred.label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str = processor.batch_decode(pred_ids)
    # we do not want to group tokens when computing the metrics
    label_str = processor.batch_decode(pred.label_ids, group_tokens=False)

    wer = wer_metric.compute(predictions=pred_str, references=label_str)
    cer = cer_metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer, "cer": cer}

In [ ]:
model.freeze_feature_encoder()

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
  output_dir="/content/gdrive/MyDrive/material project sm/model3",
  group_by_length=True,
  per_device_train_batch_size=32,
  gradient_accumulation_steps=2,
  eval_strategy="epoch",
  num_train_epochs=50,
  fp16=True,
  save_steps=1000,
  eval_steps=500,
  logging_steps=1000,
  learning_rate=2e-4,
  warmup_steps=1000,
  save_total_limit=2,
  report_to="none",
  remove_unused_columns=False,
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    data_collator=data_collator,
    args=training_args,
    compute_metrics=compute_metrics,
    train_dataset=train,
    eval_dataset=valid,
    tokenizer=processor.feature_extractor,
)

<ipython-input-54-986cab202acb>:3: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

# **Train model**

In [ ]:
trainer.train()

Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.

TrainOutput(global_step=6075, training_loss=3.1068337836873874, metrics={'train_runtime': 23356.717, 'train_samples_per_second': 24.974, 'train_steps_per_second': 0.26, 'total_flos': 5.009532019899679e+19, 'train_loss': 3.1068337836873874, 'epoch': 24.899383983572896})

# **Train model 2**

In [ ]:
trainer.train()

Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.

Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.

TrainOutput(global_step=8900, training_loss=1.2269237595461728, metrics={'train_runtime': 28647.3453, 'train_samples_per_second': 29.849, 'train_steps_per_second': 0.311, 'total_flos': 7.909502462727635e+19, 'train_loss': 1.2269237595461728, 'epoch': 24.931276297335202})

# **Train model 3**

In [ ]:
trainer.train()

/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(

Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.

Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
Trainer.tokenizer is now deprecated. You should use Trainer.processing_class instead.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py:174: UserWarning: `as_target_processor` is deprecated and will be removed in v5 of Transformers. You can process your labels by using the argument `text` of the regular `__call__` method (either in the same call as your audio inputs, or in a separate call.
  warnings.warn(

TrainOutput(global_step=26700, training_loss=0.5971419859468268, metrics={'train_runtime': 59156.9775, 'train_samples_per_second': 28.91, 'train_steps_per_second': 0.451, 'total_flos': 1.579111410162711e+20, 'train_loss': 0.5971419859468268, 'epoch': 49.90739008419083})

# **Save model to google drive**

In [ ]:
# /content/gdrive/MyDrive/material project sm/model | /content/gdrive/MyDrive/material project sm/model2
model_save_path = "/content/gdrive/MyDrive/material project sm/model_50epoch"

model.save_pretrained(model_save_path)

processor.save_pretrained(model_save_path)

print(f"Model and processor saved to: {model_save_path}")

Model and processor saved to: /content/gdrive/MyDrive/material project sm/model_50epoch

In [ ]:
processor.save_pretrained("/content/wav2vec2-demo-thai")

[]

# **Test model**

In [ ]:
model = Wav2Vec2ForCTC.from_pretrained("/content/gdrive/MyDrive/material project sm/model_50epoch").to("cuda")
processor = Wav2Vec2Processor.from_pretrained("/content/gdrive/MyDrive/material project sm/model_50epoch")

In [ ]:
input_dict = processor(valid["input_values"][1], return_tensors="pt", padding=True)

logits = model(input_dict.input_values.to("cuda")).logits

pred_ids = torch.argmax(logits, dim=-1)[0]

It is strongly recommended to pass the ``sampling_rate`` argument to this function. Failing to do so can result in silent errors that might be hard to debug.

In [ ]:
print("Prediction:")
print(processor.decode(pred_ids))

print("\nReference:")
print(common_voice_valid[1]["sentence"].lower())

Prediction:
อนวคต ของ การ ดูแล สุขภาพ ได้ รับ การ สนับสนุน จาก เครื่องมือ การ วิฉัย โดย ใช้ คอมพิวเตอร์

Reference:
อนาคต ของ การ ดูแล สุขภาพ ได้ รับ การ สนับสนุน จาก เครื่องมือ การ วินิจฉัย โดย ใช้ คอมพิวเตอร์